import { KoeficijentConfiguration } from "./types";

export const koeficijenti = {
  "ravnatelj KBC-a i kliničkih bolnica": 3.395,
  "ravnatelj Hrvatskog zavoda za javno zdravstvo": 3.395,
  "zamjenik ravnatelja KBC-a kliničkih bolnica i Hrvatskog zavoda za javno zdravstvo": 3.104,
  "ravnatelj drugih kliničkih ustanova": 3.104,
  "ravnatelj drugih državnih zdravstvenih zavoda": 3.104,
  "zamjenik ravnatelja drugih kliničkih ustanova i drugih državnih zdravstvenih zavoda": 2.813,
  "ravnatelj županijske bolnice": 2.813,
  "ravnatelj županijskog Doma zdravlja i Doma zdravlja Grada Zagreba": 2.813,
  "ravnatelj županijskog Zavoda za javno zdravstvo i županijskog Zavoda za hitnu medicinu": 2.716,
  "zamjenik ravnatelja županijske bolnice županijskog Doma zdravlja Doma zdravlja Grada Zagreba i županijskog Zavoda za javno zdravstvo i županijskog Zavoda za hitnu medicinu": 2.522,
  "ravnatelj Doma zdravlja i ljekarničke ustanove": 2.279,
  "predstojnik klinike, predstojnik kliničkog zavoda u kliničkoj ustanovi": 3.007,
  "pomoćnik ravnatelja KBC-a i kliničkih bolnica i Hrvatskog zavoda za javno zdravstvo": 3.007,
  "pomoćnik ravnatelja drugih kliničkih ustanova i drugih državnih zdravstvenih zavoda": 2.716,
  "pomoćnik ravnatelja županijske bolnice županijskog Doma zdravlja Doma zdravlja Grada Zagreba i županijskog Zavoda za javno zdravstvo i županijskog Zavoda za hitnu medicinu": 2.425,
  "pomoćnik ravnatelja Doma zdravlja i ljekarničke ustanove": 1.891,
  "pročelnik kliničkog odjela, pročelnik zavoda, centra, dnevne bolnice klinike, poliklinike u kliničkoj ustanovi, dr. sc.": 2.687,
  "pročelnik kliničkog odjela, pročelnik zavoda, centra, dnevne bolnice klinike, poliklinike u kliničkoj ustanovi, mr. sc.": 2.57,
  "pročelnik kliničkog odjela, pročelnik zavoda, centra, dnevne bolnice klinike, poliklinike u kliničkoj ustanovi, prim.": 2.522,
  "pročelnik kliničkog odjela, pročelnik zavoda, centra, dnevne bolnice klinike, poliklinike u kliničkoj ustanovi": 2.444,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi preko 40 zaposlenih, dr. sc.": 2.687,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi preko 40 zaposlenih, mr. sc.": 2.57,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi preko 40 zaposlenih, prim.": 2.522,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi preko 40 zaposlenih": 2.444,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi do 40 zaposlenih, dr. sc.": 2.638,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi do 40 zaposlenih, mr. sc.": 2.522,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi do 40 zaposlenih, prim.": 2.473,
  "voditelj zdravstvenog odjela, voditelj dnevne bolnice zavoda, poliklinike u državnoj ustanovi do 40 zaposlenih": 2.406,
  "voditelj zdravstvene službe u državnom zdravstvenom zavodu": 2.716,
  "pročelnik zdravstvene službe, pročelnik dnevne bolnice u županijskoj bolnici": 2.444,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove preko 40 zaposlenih, dr. sc.": 2.541,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove preko 40 zaposlenih, mr. sc.": 2.425,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove preko 40 zaposlenih, prim.": 2.376,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove preko 40 zaposlenih": 2.318,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove do 40 zaposlenih, dr. sc.": 2.493,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove do 40 zaposlenih, mr. sc.": 2.386,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove do 40 zaposlenih prim.": 2.328,
  "voditelj zdravstvenog odjela, dnevne bolnice, centra, poliklinike županijske ustanove do 40 zaposlenih": 2.279,
  "glavna sestra/glavni tehničar državne ustanove": 1.659,
  "glavna sestra klinike kao samostalne ustanove": 1.571,
  "glavna sestra/glavni tehničar županijske ustanove": 1.571,
  "glavna sestra/glavni tehničar u državnoj ustanovi, glavna sestra/glavni tehničar u županijskoj ustanovi, glavna sestra klinike, glavna sestra, zdravstveni djelatnik  voditelj odjela": 1.164,
  "doktor medicine specijalist, uži specijalist, dr. sc. u bolnici, državnom zdravstvenom zavodu": 2.361,
  "doktor medicine specijalist, uži specijalist mr. sc. u bolnici, državnom zdravstvenom zavodu": 2.336,
  "doktor medicine specijalist, uži specijalist prim. u bolnici, državnom zdravstvenom zavodu": 2.317,
  "doktor medicine specijalist, uži specijalist u bolnici, državnom zdravstvenom zavodu": 2.298,
  "doktor medicine specijalist, uži specijalist dr. sc.": 2.33,
  "doktor medicine specijalist, uži specijalist mr. sc.": 2.27,
  "doktor medicine specijalist, uži specijalist prim.": 2.21,
  "doktor medicine specijalist, uži specijalist": 2.14,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim. dr. sc. u bolnici, državnom zdravstvenom zavodu": 2.279,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim. mr. sc. u bolnici, državnom zdravstvenom zavodu": 2.182,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim. u bolnici, državnom zdravstvenom zavodu": 2.085,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim. dr. sc.": 2.153,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim. mr. sc.": 2.056,
  "doktor medicine specijalist i doktor dentalne medicine specijalist prim.": 1.969,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist, dr. sc. u bolnici, državnom zdravstvenom zavodu": 2.153,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist, mr. sc. u bolnici, državnom zdravstvenom zavodu": 2.056,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist u bolnici, državnom zdravstvenom zavodu": 2.027,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist dr. sc.": 1.988,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist mr. sc.": 1.959,
  "doktor medicine specijalist, doktor dentalne medicine specijalist, magistar medicinske biokemije specijalist, magistar farmacije specijalist": 1.94,
  "doktor medicine, doktor dentalne medicine, magistar medicinske biokemije, magistar farmacije, na specijalizaciji": 1.659,
  "ugovorni zdravstveni djelatnik primarne zdravstvene zatite dr. sc.": 1.959,
  "ugovorni zdravstveni djelatnik primarne zdravstvene zatite primarijus": 1.921,
  "ugovorni zdravstveni djelatnik primarne zdravstvene zatite mr. sc.": 1.882,
  "ugovorni zdravstveni djelatnik primarne zdravstvene zatite": 1.794,
  "nezdravstveni djelatnik voditelj djelatnosti koji sudjeluje u procesu dijagnostike i liječenja, dr. sc. u bolnici, državnom zdravstvenom zavodu": 1.988,
  "nezdravstveni djelatnik voditelj djelatnosti koji sudjeluje u procesu dijagnostike i liječenja, mr. sc. u bolnici, državnom zdravstvenom zavodu": 1.901,
  "nezdravstveni djelatnik voditelj djelatnosti koji sudjeluje u procesu dijagnostike i liječenja u bolnici, državnom zdravstvenom zavodu": 1.824,
  "doktor medicine, doktor dentalne medicine, magistar medicinske biokemije, magistar farmacije, dr. sc.": 1.804,
  "doktor medicine, doktor dentalne medicine, magistar medicinske biokemije, magistar farmacije, mr. sc.": 1.727,
  "doktor medicine, doktor dentalne medicine, magistar medicinske biokemije, magistar farmacije": 1.659,
  "zdravstveni djelatnik u zdravstvenom zavodu": 1.659,
  "logoped": 1.571,
  "nezdravstveni djelatnik koji sudjeluje u procesu dijagnostike i liječenja, dr. sc.": 1.571,
  "molekularni biolog, biolog, citogenetičar, psiholog, fonetičar, fizičar, defektolog/edukacijski rehabilitator, koji sudjeluje u procesu dijagnostike i liječenja": 1.571,
  "nezdravstveni djelatnik koji sudjeluje u procesu dijagnostike i liječenja, mr. sc.": 1.513,
  "nezdravstveni djelatnik koji sudjeluje u procesu dijagnostike i liječenja": 1.445,
  "zdravstveni djelatnik, pripravnik": 1.115,
  "zdravstveni djelatnik u bolnici, poliklinikama, primarnoj zdravstvenoj zatiti i javnom zdravstvu": 1.164,
  "nezdravstveni djelatnici, zdravstveni suradnici": 1.125,
  "zdravstveni djelatnik na otvorenim izvorima zračenja, citostaticima, liječenju AIDS-a, u jedinici intenzivne skrbi u operaciji (instrumentiranje, anesteziologija),na hemodijalizi, u rađaonici, hitnoj službi i traumatologiji": 1.067,
  "zdravstveni djelatnik u bolnici i kućnoj njezi": 1.018,
  "zdravstveni djelatnik u primarnoj zdravstvenoj zatiti, poliklinikama, javnom zdravstvu, vozač (samo djelatnost hitne medicine)": 0.951,
  "bolničar": 0.727,
};
